import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { atkinsonHyperlegible, libreBaskerville } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${atkinsonHyperlegible.variable} ${libreBaskerville.variable} font-sans antialiased overflow-hidden`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange={false}
        >
          <div className="h-screen w-screen p-2 md:p-4 m-0 flex overflow-hidden ">
            <main className="w-full rounded-3xl overflow-y-auto bg-secondary/30">
              {children}
            </main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
